<conf> :== [<server>]*
<server> :== "server" "{" [<server_conf>]* "}"
<server_conf>  :== "listen" <listen_ip> ":" <port> ";"
                | "location" "path" "{" [<location_conf>]* "}"
                | "error_page" [<number> " "]+ <string>.html ";"
                ;

<location_conf> :== 

<listen_addr> :== <ip> ":" <port>
                    | <ip>
                    | <port>
                    ;
<ip> :== // 127.0.0.1
<port> :== <number>

<number> :== [1-9][0-9]*
<string> :== [a-zA-Z_./]+
